INSERT INTO Resposta(texto) VALUES('Um');
INSERT INTO Resposta(texto) VALUES('Dois');
INSERT INTO Resposta(texto) VALUES('Três');
INSERT INTO Resposta(texto) VALUES('Quatro');
INSERT INTO Resposta(texto) VALUES('Cinco');
INSERT INTO Resposta(texto) VALUES('Seis');
INSERT INTO Resposta(texto) VALUES('Sete');
INSERT INTO Resposta(texto) VALUES('Oito');
INSERT INTO Resposta(texto) VALUES('Nove');
INSERT INTO Resposta(texto) VALUES('Dez');

INSERT INTO Resposta(texto) VALUES('Avião');
INSERT INTO Resposta(texto) VALUES('Açucar');
INSERT INTO Resposta(texto) VALUES('Borracha');
INSERT INTO Resposta(texto) VALUES('Brasil');
INSERT INTO Resposta(texto) VALUES('Cachorro');
INSERT INTO Resposta(texto) VALUES('Caderno');
INSERT INTO Resposta(texto) VALUES('Caneca');
INSERT INTO Resposta(texto) VALUES('Carro');
INSERT INTO Resposta(texto) VALUES('Celular');
INSERT INTO Resposta(texto) VALUES('Chocolate');
INSERT INTO Resposta(texto) VALUES('Elefante');
INSERT INTO Resposta(texto) VALUES('Futebol');
INSERT INTO Resposta(texto) VALUES('Internet');
INSERT INTO Resposta(texto) VALUES('Lápis');
INSERT INTO Resposta(texto) VALUES('Livro');
INSERT INTO Resposta(texto) VALUES('Lua');
INSERT INTO Resposta(texto) VALUES('Sapato');
INSERT INTO Resposta(texto) VALUES('Televisão');

INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Quanto é 3 mais 1?', 																					(SELECT id FROM Resposta WHERE texto='Quatro') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual dos itens abaixo contém cacau em sua composição?', 												(SELECT id FROM Resposta WHERE texto='Chocolate') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Quanto é 5 mais 5?', 																					(SELECT id FROM Resposta WHERE texto='Dez') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual dos itens abaixo contém 4 rodas?', 																(SELECT id FROM Resposta WHERE texto='Carro') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual o nome do satélite de nosso planeta Terra?', 													(SELECT id FROM Resposta WHERE texto='Lua') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual animal é o melhor amigo do homem?', 																(SELECT id FROM Resposta WHERE texto='Cachorro') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual país é conhecido pelo Futebol e Carnaval?',														(SELECT id FROM Resposta WHERE texto='Brasil') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual é o meio de transporte que voa?',																(SELECT id FROM Resposta WHERE texto='Avião') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual é a Rede Mundial de Computadores?',																(SELECT id FROM Resposta WHERE texto='Internet') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Qual item escolar é composto de madeira, grafite e pode-se apontá-lo?',								(SELECT id FROM Resposta WHERE texto='Lápis') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Com qual item escolar pode-se apagar textos a lápis e é composto por Látex?',							(SELECT id FROM Resposta WHERE texto='Borracha') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Com qual aparelho físico eletrônico é possível ligar e conversar com outras pessoas a distância?',	(SELECT id FROM Resposta WHERE texto='Celular') );
INSERT INTO Pergunta(texto, resposta_id) VALUES( 'Com qual item abaixo é possível adoçar alimentos e líquidos?',										(SELECT id FROM Resposta WHERE texto='Açucar') );
